### ISSUE TITLE
게시글에서 Category 설정시 출력 오류 발생

### ISSUE THREAD

**Issue by knh4437** [DogamDogam/Frontend#9]
정렬 버튼에서 식재료 선택시 식재료 게시글이 잘 나오지만
다시 정렬로 전환하고, 배달비 선택시 식재료 게시글이 출력됨
- 정렬 -> 식재료 -> 정렬 -> 배달비시 식재료 게시글 출력됨 @ @

**Comment by dhgkdud12** [comment]
categoryPostBox 코드 수정하여 해결하였습니다.
